# Generated by Django 3.2.23 on 2024-03-27 06:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictiondata',
            name='submitted_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
